package componentes;

import java.util.*;

import java.util.HashSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Jhoan López
 */

public class ComponenteDni extends javax.swing.JPanel {

    public String getLabel() {
        return jl_campoNombre.getText();
    }
    public void setLabel(String label){
        jl_campoNombre.setText(label);
    }
    
    public String getDNI() {
        return tf_campoDni.getText();
    }
    public void setDNI(String textField) {
        tf_campoDni.setText(textField);
    }
    
    public String getMesaage() {
        return jl_mensaje.getText();
    }
    public void setMensaje(String label) {
        jl_mensaje.setText(label);
    }
    
    
    public ComponenteDni() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_campoNombre = new javax.swing.JLabel();
        tf_campoDni = new javax.swing.JTextField();
        jl_mensaje = new javax.swing.JLabel();

        jl_campoNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jl_campoNombre.setText("DNI");

        tf_campoDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_campoDniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_campoDniFocusLost(evt);
            }
        });
        tf_campoDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_campoDniActionPerformed(evt);
            }
        });

        jl_mensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_mensaje.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_campoNombre)
                    .addComponent(tf_campoDni, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jl_mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_campoNombre)
                .addGap(18, 18, 18)
                .addComponent(tf_campoDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_campoDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_campoDniFocusLost
        String DNI_LETRAS = "TRWAGMYFPDXBNJZSQVHLCKE";
        String dniIntroducido = getDNI();
        // Verificar que la cadena tiene 8 dígitos y una letra
        //
        // ([0-9]{8})-?([a-zA-Z])
        
        Pattern patronDNI = Pattern.compile("([0-9]{8})-?([a-zA-Z])");
        Matcher matchDNI = patronDNI.matcher(dniIntroducido);
        if(!matchDNI.matches()) {
            setMensaje("Formato de DNI erróneo");
            return;
        }
        
        // Separar números y letra
        String cadenaNumeros = matchDNI.group(1);
        String letraDNI = matchDNI.group(2);
                
        // Hacer validación
        Integer numeroDNI = Integer.parseInt(cadenaNumeros);
        int posicionLetra = numeroDNI % 23;
        String letraEsperada = DNI_LETRAS.substring(posicionLetra, posicionLetra + 1);
        
        if(!letraEsperada.equalsIgnoreCase(letraDNI)) {
            setMensaje("El número y la letra no concuerdan");
            return;
        }   
    }//GEN-LAST:event_tf_campoDniFocusLost

    private void tf_campoDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_campoDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_campoDniActionPerformed

    private void tf_campoDniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_campoDniFocusGained
        jl_mensaje.setText("");
    }//GEN-LAST:event_tf_campoDniFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_campoNombre;
    private javax.swing.JLabel jl_mensaje;
    private javax.swing.JTextField tf_campoDni;
    // End of variables declaration//GEN-END:variables
}
