package componentes;

/**
 *
 * @author Jhoan López
 */
public class LoginTarjetas extends javax.swing.JPanel {

    
    public LoginTarjetas() {
        initComponents();
    }

    public String getText() {
        return tf_numTarjeta.getText();
    }
    public void setText (String texto) {
        tf_numTarjeta.setText(texto);
    }
    
    public String getLabel() {
        return jl_numero.getText();
    }
    public void setLabel(String texto) {
        jl_numero.setText(texto);
    }
    
    public String getComboBoxMes () {
        return cb_meses.getSelectedItem().toString();
    }
    
    public String getComboBoxAno () {
        return cb_años.getSelectedItem().toString();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        componenteDni1 = new componentes.ComponenteDni();
        jl_titular = new javax.swing.JLabel();
        tf_nombreTitular = new javax.swing.JTextField();
        jl_numero = new javax.swing.JLabel();
        tf_numTarjeta = new javax.swing.JTextField();
        jl_infoNumTarjeta = new javax.swing.JLabel();
        jl_fechaCaducidad = new javax.swing.JLabel();
        cb_meses = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_años = new javax.swing.JComboBox<>();
        jl_cvv = new javax.swing.JLabel();
        tf_cvc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jl_infoCvv = new javax.swing.JLabel();

        jl_titular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_titular.setText("Títular");

        tf_nombreTitular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nombreTitularKeyTyped(evt);
            }
        });

        jl_numero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_numero.setText("Número");

        tf_numTarjeta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_numTarjetaFocusLost(evt);
            }
        });
        tf_numTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_numTarjetaKeyTyped(evt);
            }
        });

        jl_infoNumTarjeta.setPreferredSize(new java.awt.Dimension(37, 15));

        jl_fechaCaducidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_fechaCaducidad.setText("Fecha Caducidad");

        cb_meses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_meses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" /");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cb_años.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cb_años.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026" }));
        cb_años.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_añosActionPerformed(evt);
            }
        });

        jl_cvv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jl_cvv.setText("CVV");

        tf_cvc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_cvc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_cvcFocusLost(evt);
            }
        });
        tf_cvc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_cvcKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("VALIDAR");

        jl_infoCvv.setPreferredSize(new java.awt.Dimension(37, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_fechaCaducidad)
                        .addGap(18, 18, 18)
                        .addComponent(cb_meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_titular)
                            .addComponent(jl_numero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_numTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                            .addComponent(tf_nombreTitular)
                            .addComponent(jl_infoNumTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_cvv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_cvc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(jl_infoCvv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_nombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_titular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_numTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_numero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_infoNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_fechaCaducidad)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_cvv)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_infoCvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb_añosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_añosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_añosActionPerformed

    private void tf_cvcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_cvcKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57 || key == 8 || key == 127;
        tf_cvc.setEditable(true);
        
        if (!numeros) {
            evt.consume();
            jl_infoCvv.setText("Este campo solo contiene números");
        } else if (tf_cvc.getText().length() > 3) {
            evt.consume(); 
            jl_infoCvv.setText("Este campo contiene máximo 4 díjitos");
        } else if (tf_cvc.getText().length() < 3) {
            jl_infoCvv.setText("Este campo contiene mínimo 3 díjitos");
        } else {
            jl_infoCvv.setText("");
        }
    }//GEN-LAST:event_tf_cvcKeyTyped

    private void tf_nombreTitularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nombreTitularKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 65 && key <= 90 || key >= 97 && key <= 122 || key == 32;
        tf_cvc.setEditable(true);
        
        if (!numeros) {
            evt.consume();
        } else if (tf_cvc.getText().length() >= 16) {
            evt.consume();      
        } 
    }//GEN-LAST:event_tf_nombreTitularKeyTyped

    private void tf_numTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_numTarjetaKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57 || key == 8 || key == 127;
        tf_cvc.setEditable(true);
        
        if (!numeros) {
            evt.consume();
            jl_infoNumTarjeta.setText("Este campo solo contiene números");
        } else if (tf_numTarjeta.getText().length() > 23) {
            evt.consume();
            jl_infoNumTarjeta.setText("Este campo contiene máximo 24 dígitos");
        } else if (tf_numTarjeta.getText().length() < 12) {
            jl_infoNumTarjeta.setText("Este campo contiene mínimo 13 dígitos");
        } else {
            jl_infoNumTarjeta.setText("");
        }
        
    }//GEN-LAST:event_tf_numTarjetaKeyTyped

    private void tf_cvcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_cvcFocusLost
        if (tf_cvc.getText().length() > 2) {
            jl_infoCvv.setText("");
        }
    }//GEN-LAST:event_tf_cvcFocusLost

    private void tf_numTarjetaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_numTarjetaFocusLost
        if (tf_numTarjeta.getText().length() > 12) {
        jl_infoNumTarjeta.setText("");
        }
    }//GEN-LAST:event_tf_numTarjetaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_años;
    private javax.swing.JComboBox<String> cb_meses;
    private componentes.ComponenteDni componenteDni1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jl_cvv;
    private javax.swing.JLabel jl_fechaCaducidad;
    private javax.swing.JLabel jl_infoCvv;
    private javax.swing.JLabel jl_infoNumTarjeta;
    private javax.swing.JLabel jl_numero;
    private javax.swing.JLabel jl_titular;
    private javax.swing.JTextField tf_cvc;
    private javax.swing.JTextField tf_nombreTitular;
    private javax.swing.JTextField tf_numTarjeta;
    // End of variables declaration//GEN-END:variables
}
